#!/bin/bash

# configuration setup #
git config --global user.name "acduroy"
git config --global user.mail "acduroy@yahoo.com"
git config --global color.ui auto

# create repositories #
mkdir $1
git init $1
git clone https://github.com/acduroy/$1.git

exit 0

