#! /bin/sh

### BEGIN INIT INFO
# Provides:          myupdate
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
    start)
        ~/bridge-network/maas-cert-install.sh
        ;;
    stop|restart|reload)
        ;;
esac
